routes/admin.php
<?php

use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\University\AdmissionController;
use App\Http\Controllers\University\CollegeController;
use App\Http\Controllers\University\UniversityController;
use App\Http\Controllers\University\CommonSettingController;
use App\Http\Controllers\University\StudentController;
use App\Http\Controllers\University\CourseController;
use App\Http\Controllers\University\MeritRoundController;

Route::group(['namespace' => 'Auth'], function () {
    # Login Routes
    Route::get('login', 'LoginController@showLoginForm');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('admin/logout', 'LoginController@logout')->name('logout');
});

Route::group(['middleware' => 'auth:admin'], function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');

    Route::group(['prefix' => 'admin'], function () {
        Route::get('profile', [UniversityController::class, 'profile'])->name('admin.profile');
        Route::post('profile', [UniversityController::class, 'updateprofile']);
    });

    Route::group(['prefix'=>'college'],function(){
        Route::get('create',[CollegeController::class,'create'])->name('college.create');
        Route::get('index',[CollegeController::class,'index'])->name('college.index');
        Route::post('store',[CollegeController::class,'store'])->name('college.store');
        Route::get('edit/{id}',[CollegeController::class,'edit'])->name('college.edit');
        Route::post('update',[CollegeController::class,'update'])->name('college.update');
        Route::post('destroy',[CollegeController::class,'destroy'])->name('college.destroy');
    });   
        
    Route::group(['prefix'=>'common_setting','as'=>'common_setting.'],function(){
        Route::get('create',[CommonSettingController::class,'create'])->name('create');
        Route::get('index',[CommonSettingController::class,'index'])->name('index');
        Route::post('store',[CommonSettingController::class,'store'])->name('store');
        Route::get('edit/{id}',[CommonSettingController::class,'edit'])->name('edit');
        Route::post('update',[CommonSettingController::class,'update'])->name('update');
        Route::post('destroy',[CommonSettingController::class,'destroy'])->name('destroy');
    });  

    Route::group(['prefix'=>'student','as'=>'student.'],function(){
        Route::get('create',[StudentController::class,'create'])->name('create');        
        Route::get('index',[StudentController::class,'index'])->name('index');
        Route::post('destroy',[StudentController::class,'destroy'])->name('destroy');
    });
    
    
    Route::group(['prefix'=>'course','as'=>'course.'],function(){
        Route::get('create',[CourseController::class,'create'])->name('create');        
        Route::get('index',[CourseController::class,'index'])->name('index');
        Route::get('edit/{id}',[CourseController::class,'edit'])->name('edit');
        Route::post('update',[CourseController::class,'update'])->name('update');
        Route::post('destroy',[CourseController::class,'destroy'])->name('destroy');
    });


    Route::group(['prefix'=>'merit','as'=>'merit.'],function(){
        Route::get('create',[MeritRoundController::class,'create'])->name('create');        
        Route::get('index',[MeritRoundController::class,'index'])->name('index');
        Route::post('store',[MeritRoundController::class,'store'])->name('store');
        Route::get('edit/{id}',[MeritRoundController::class,'edit'])->name('edit');
        Route::post('update',[MeritRoundController::class,'update'])->name('update');
        Route::post('destroy',[MeritRoundController::class,'destroy'])->name('destroy');
    });


    Route::group(['prefix'=>'admission','as'=>'admission.'],function(){
        Route::get('create',[AdmissionController::class,'create'])->name('create');        
        Route::get('index',[AdmissionController::class,'index'])->name('index');
        Route::post('destroy',[AdmissionController::class,'destroy'])->name('destroy');
    });
});


?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Student extends Authenticatable
{
    use HasFactory;

    protected $fillable = [
        'name','email','contact_no','email_verified_at','gender','address','otp','password','adhaar_card_no','image'
    ];
}

app/Http/Controllers/Student/AdmissionConfirmController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Models\Addmission;
use App\Models\AddmissionConfirmations;
use App\Models\MeritRound;
use App\Repository\AdmissionConfirmeRepository;
use Illuminate\Http\Request;

class AdmissionConfirmController extends Controller
{
    public function __construct(AdmissionConfirmeRepository $admissionconfirmRepository)
    {
        $this->admissionconfirmRepository = $admissionconfirmRepository;
    }

    public function store(Request $request)
    {
        $store = $this->admissionconfirmRepository->store($request);
        return response()->json($store); 
    }

    public function changeStatus(Request $request)
    {
        $user = Addmission::find($request->user_id);
        $user->status = $request->data_status;
        if ($request->data_status == 2) {
            $message = 'Rejected';
        } else if ($request->data_status == 0) {
            $message = 'You will appear next round';
        } else if ($request->data_status == 1) {
            $message = 'You will be selected';
        }else {
            $message = '';
        }
        $user->save();
        return response()->json(['message' => $message]);
    }
}

app/Http/Controllers/Student/AdmissionController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admission\StoreRequest;
use App\Models\Addmission;
use App\Models\College;
use App\Models\Course;
use App\Models\MeritRound;
use App\Models\StudentMark;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Validator;

class AdmissionController extends Controller
{
    public function create()
    {
        $course = Course::get();
        $collage = College::get();
        $merit_round = MeritRound::get();
        $dateYmd = date('Y-m-d');
        $form = MeritRound::where('start_date','<=',$dateYmd)->where('end_date','>=',$dateYmd)->first();
        return view('student.admission.create',compact('course','merit_round','collage','form'));
    }

    public function store(StoreRequest $request)
    {
        // $studentmark = StudentMark::with('commonsetting')->where('id', Auth::guard('student')->user()->id)->get();
        // // dd($studentmark);
        // $merit = 0;
        // $com_total = 0;
        // foreach ($studentmark as $studentmarks) {
        //     $total = ($studentmarks->obtain_mark * $studentmarks->commonsetting['marks'] ?? 0) / 100;
        //     $merit = $merit + $total;
        //     $com_total = $com_total + $studentmarks->commonsetting['marks'];
        // }
        // $f_merit = $merit / $com_total * 100;
        // dd($f_merit);        
        // dd($form);
        
        $student = StudentMark::where('id',Auth()->user()->id)->get();                   
        $course = Course::where('id',$request->course_id)->pluck('name')->first();  
        $addmission_code  = getRandomString($length = 6);
        $admission = new Addmission;
        $admission->user_id = request()->user()->id;
        $admission->merit = $request->merit;
        $admission->college_id = $request->college_id;
        $admission->addmission_date = $request->addmission_date;
        $admission->course_id = $request->course_id;    
        $admission->addmission_code = strtoupper($course) . $addmission_code;
        $admission->merit_round_id = $request->merit_round_no;
        $admission->status = 3;
        $admission->save();
        return response()->json('1');
    }  
    
    public function index(Request $request)
    {                
        $admission = Addmission::where('user_id',Auth()->user()->id)->first();              
        // $status = Addmission::where('user_id',Auth()->user()->id)->where('status',2)->first();               
        return view('student.admission.index',compact('admission'));
    }    
}
?>

app/Http/Controllers/Student/StudentController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;

class StudentController extends Controller
{
    public function profile()
    {
        $admin = Auth::guard('student')->user();
        return view('student.profile',compact('admin'));
    }

    public function updateprofile(Request $request)
    {              
        $admin = Auth::guard('student')->user();
        if ($request->hasFile('image')) {
            $destination = 'app/public/' . $admin->image;
            if (File::exists($destination)) {
                File::delete($destination);
            }
            $file = $request->file('image');
            $name = $file->getClientOriginalName();
            $file->move('app/public/', $name);
            $admin->image = $name;
        }
        $admin->name = $request->name;
        $admin->address = $request->address;
        $admin->save();
        session()->flash('update','Profile updated successfully');
        return redirect()->back();
    }

    public function changepassword()
    {
        return view('student.change_password');
    }

    public function updatepassword(Request $request)
    {
        $hashedPassword = Auth::guard('student')->user()->password;
        if (Hash::check($request->oldpassword, $hashedPassword)) {
            $update = bcrypt($request->newpassword);
            $users = Auth::guard('student')->id();
            $id = User::where('id', $users)->update(['password' => $update]);
            if ($id) {
                session()->flash('update', 'password updated successfully');
            }
            return redirect()->back();
        } else {
            session()->flash('error', 'old password doesnt matched');
            return redirect()->back();
        }
    }

}

app/Http/Controllers/Student/StudentMarkController.php
<?php

namespace App\Http\Controllers\Student;

use App\DataTables\StudentMarkDataTable;
use App\Http\Controllers\Controller;
use App\Http\Requests\StudentMark\StoreRequest;
use App\Models\StudentMark;
use App\Models\Subject;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class StudentMarkController extends Controller
{
    public function index(StudentMarkDataTable $studentmarkDataTable)
    {
        return  $studentmarkDataTable->render('student.mark.index');
    }

    public function create()
    {
        $subject = Subject::select('id', 'name')->get();
        return view('student.mark.create', compact('subject'));
    }

    public function store(StoreRequest $request)
    {
        $user_id = request()->user()->id;
        foreach ($request['subject_id'] as $key => $data) {
            StudentMark::create([
                'user_id' => $user_id,
                'subject_id' => $key,
                'total_mark' => $request->total_mark,
                'obtain_mark' => $data
            ]);
        }
        return response()->json('1');
    }

    public function edit(Request $id)
    {
        $subject = Subject::findOrFail($id);
        $student_mark = StudentMark::with('Subject')->where('user_id', Auth::guard('student')->user()->id)->get();
        return view('student.mark.edit', compact('student_mark'));
    }

    public function update(Request $request)
    {
        dd($request->all());
        $student_mark = StudentMark::find($request->id);
        $student_mark->subject_id = $request->subject_id;
        $student_mark->save();
        return response()->json(['property' => $student_mark]);
    }
}

app/Http/Controllers/University/StudentController.php
<?php

namespace App\Http\Controllers\University;

use App\DataTables\StudentDataTable;
use App\DataTables\UserDataTable;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    public function index(UserDataTable $userDataTable)
    {
        return  $userDataTable->render('admin.student.index') ;     
    }

    public function destroy(Request $request)
    {
        $student = User::where('id',$request->id)->delete();
        return response()->json(['student'=>$student]);
    }

}

resources/views/student/change_password.blade.php
@extends('layouts.student.master')
@section('title','ChangePassword')
@push('css')
<style>
    .error{
        color:red;
    }
</style>
@endpush
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Change Password
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Change Password</li>
        </ol>
    </section>
    <section class="content ">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-6">
                @if($message = Session::get('update'))
                <div class="alert alert-success" class="close" id="success">
                    {{$message}}
                </div>
                @endif

                @if($message = Session::get('error'))
                <div class="alert alert-danger" class="close" id="success">
                    {{$message}}
                </div>
                @endif
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li><a href="#settings" data-toggle="tab">ChangePassword</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="settings">
                            <form class="form-horizontal" id="changepass" method="post" action="" id="profileupdate">
                                @csrf
                                <div class="form-group">
                                    <label for="inputEmail" class="col-sm-2 control-label">OldPassword</label>
                                    <div class="col-sm-10">
                                        <input type="password" class="form-control" id="inputEmail" name="oldpassword" placeholder="Enter Old Password">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="inputEmail" class="col-sm-2 control-label">NewPassword</label>
                                    <div class="col-sm-10">
                                        <input type="password" class="form-control" id="inputPassword" name="newpassword" placeholder="Enter New Password">
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" id="submit" class="btn btn-danger">change Password</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<div class="control-sidebar-bg"></div>
</div>
@endsection
@push('js')
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.0/jquery.validate.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.0/additional-methods.js"></script>
<script>    
    $('#changepass').validate({
        rules: {
            oldpassword: {
                required: true
            },
            newpassword: {
                required: true
            }
        },
        messages: {
            oldpassword: {
                required: "Please enter oldpassword"
            },
            newpassword: {
                required: "Please enter newpassword"
            }
        },
        submitHandler: function(form) {
            submit.form();
        }
    });
</script>
@endpush

resources/views/student/dashboard.blade.php
@extends('layouts.student.master')
@section('title','Dashboard')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Dashboard           
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>20</h3>
                        <p>Total Book</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>53<sup style="font-size: 20px">%</sup></h3>
                        <p>Bounce Rate</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>44</h3>
                        <p>User Registrations</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3>65</h3>

                        <p>Unique Visitors</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
      

    </section>
</div>

@endsection

 

resources/views/student/login.blade.php
<!DOCTYPE html>
<html>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>UMS | Log in</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{asset('asset/css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{asset('asset/css/font-awesome.min.css')}}">
  <link rel="stylesheet" href="{{asset('asset/css/ionicons.min.css')}}">
  <link rel="stylesheet" href="{{asset('asset/css/AdminLTE.min.css')}}">
  <link rel="stylesheet" href="{{asset('asset/css/blue.css')}}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <a href="../../index2.html"><b>Student</b>Sign in</a>
    </div>
    <div class="login-box-body">
      <p class="login-box-msg">Sign in to start your session</p>
      <form action="{{ route('student.login') }}" id="myform" method="post">
        @csrf
        <div class="form-group has-feedback">
          <input type="text" class="form-control" name="email" placeholder="Email">
        </div>
        @if(session()->has('message'))          
          <span class="invalid-feedback" role="alert">
            <strong class="error">{{ session()->get('message') }}</strong>
          </span>
        @endif
        <div class="form-group has-feedback">
          <input type="password" class="form-control" name="password" placeholder="Password">
        </div>
        @error('password')
        <span class="invalid-feedback" role="alert">
          <strong>{{ $message }}</strong>
        </span>
        @enderror
        <div class="row">
          <div class="col-xs-4">
            <button type="submit" name="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
          </div>
        </div>
      </form>
      <a href="#">I forgot my password</a><br>
      <a href="{{route('student.register')}}" class="text-center">Register a new membership</a>

    </div>
  </div>
  <script src="{{asset('asset/js/jquery.min.js')}}"></script>
  <script src="{{asset('asset/js/bootstrap.min.js')}}"></script>
  <script src="{{asset('asset/js/icheck.min.js')}}"></script>
</body>

</html>
  <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.0/jquery.validate.min.js"></script>
  <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.0/additional-methods.js"></script>
  <script>
    $('#myform').validate({
      rules: {
        email: {
          required: true
        },
        password: {
          required: true
        }
      },
      messages: {
        email: {
          required: "Please enter email"
        },
        password: {
          required: "Please enter password"
        }
      },
      submitHandler: function(form) {
        submit.form();
      }
    });
  </script>

resources/views/student/register.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>UMS | Registration</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <link rel="shortcut icon" href="{{ asset('asset/img/library_black.png') }}">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{{asset('asset/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/css/ionicons.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/css/AdminLTE.min.css')}}">
    <link rel="stylesheet" href="{{asset('asset/css/blue.css')}}">
    <link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition register-page">
    <div class="register-box" style="width:500px">
        <div class="register-logo">
            <a href="../../index2.html"><b>SignUp</b></a>
        </div>

        <div class="register-box-body">
            <p class="login-box-msg">Register a new student</p>
            <form id="myform" method="post">
                <div class="form-group has-feedback">
                <label>Name</label>
                    <input type="text" class="form-control" name="name" placeholder="Enter name">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>

                <div class="form-group has-feedback">
                <label>Email</label>
                    <input type="email" class="form-control" name="email" placeholder="Email">
                </div>

                <div class="form-group has-feedback">
                <label>Mobile</label>
                    <input type="text" class="form-control" name="contact_no" placeholder="Mobile">
                    <span class="glyphicon glyphicon-mobile form-control-feedback"></span>
                </div>

                <div class="form-group has-feedback">
                <label>Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>

                <div class="radio">
                    <label>
                        <input type="radio"  name="gender" id="optionsRadios1" value="M" checked>
                        Male
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio"  name="gender" id="optionsRadios2" value="F">
                        Female
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio"  name="gender" id="optionsRadios3" value="O" >
                       Other
                    </label>
                </div>
                
                <div class="form-group">
                  <label>Address</label>
                  <textarea class="form-control" rows="3" name="address" placeholder="Enter Address"></textarea>
                </div>

                <div class="form-group has-feedback">
                <label>Aadhar Number</label>
                    <input type="text   " class="form-control" onblur="AadharValidate()" name="adhaar_card_no" id="adhaar_card_no" placeholder="Aadhar card">
                    <span id="adhaarError"></span>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>

                <div class="form-group">
                    <label>Image</label>
                    <input type="file" class="form-control" name="image" id="image" placeholder="Enter category">
                </div>

                <div class="form-group">
                    <label>DOB</label>
                    <input type="date" class="form-control" name="dob" id="dob" >
                </div>

                <div class="row">                    
                    <div class="col-xs-4">
                        <button type="submit" id="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                    </div>                
                </div>
            </form>
            <a href="{{route('student.login')}}" class="text-center">I already have a membership</a>
        </div>
    </div>
    <script src="{{asset('asset/js/jquery.min.js')}}"></script>
    <script src="{{asset('asset/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('asset/js/icheck.min.js')}}"></script>

</body>

</html>
<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.2/js/toastr.min.js"></script>
<script>
    function AadharValidate()
    {
        var  aadhar = document.getElementById("adhaar_card_no").value;
        var adharcardTwelveDigit = /^\d{12}$/;
        if (aadhar != '') {
            if (aadhar.match(adharcardTwelveDigit)) {
                return true;
            }else{
                $('#adhaarError').text('Please enter 12 digit');
                alert("Enter valid Aadhar Number");
                return false;
            }
        }    
    }

    $(document).ready(function() {
        $("#submit").click(function(e) {
            e.preventDefault();
            var form = $("#myform")[0];
            var data = new FormData(form);
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: '{{route("student.register")}}',
                type: 'post',
                data: data,
                cache: false,
                contentType: false,
                processData: false,
                dataType: 'JSON',
                success: function(result) {
                    toastr.success('Register Successfully');
                    window.location.href = '{{route("student.login")}}';
                },
                error: function(result) {
                    $.each(result.responseJSON.errors, function(i, error) {
                        $('.' + i + 'error').empty();
                        var el = $(document).find('[name="' + i + '"]');
                        el.after($('<span class="' + i + 'error" style="color: red;">' + error[0] + '</span>'));
                    });
                }
            })
        });
    })

   

</script>