routes/admin.php
<?php

use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\University\AdmissionController;
use App\Http\Controllers\University\CollegeController;
use App\Http\Controllers\University\UniversityController;
use App\Http\Controllers\University\CommonSettingController;
use App\Http\Controllers\University\StudentController;
use App\Http\Controllers\University\CourseController;
use App\Http\Controllers\University\MeritRoundController;

Route::group(['namespace' => 'Auth'], function () {
    # Login Routes
    Route::get('login', 'LoginController@showLoginForm');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('admin/logout', 'LoginController@logout')->name('logout');
});

Route::group(['middleware' => 'auth:admin'], function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');

    Route::group(['prefix' => 'admin'], function () {
        Route::get('profile', [UniversityController::class, 'profile'])->name('admin.profile');
        Route::post('profile', [UniversityController::class, 'updateprofile']);
    });

    Route::group(['prefix'=>'college'],function(){
        Route::get('create',[CollegeController::class,'create'])->name('college.create');
        Route::get('index',[CollegeController::class,'index'])->name('college.index');
        Route::post('store',[CollegeController::class,'store'])->name('college.store');
        Route::get('edit/{id}',[CollegeController::class,'edit'])->name('college.edit');
        Route::post('update',[CollegeController::class,'update'])->name('college.update');
        Route::post('destroy',[CollegeController::class,'destroy'])->name('college.destroy');
    });   
        
    Route::group(['prefix'=>'common_setting','as'=>'common_setting.'],function(){
        Route::get('create',[CommonSettingController::class,'create'])->name('create');
        Route::get('index',[CommonSettingController::class,'index'])->name('index');
        Route::post('store',[CommonSettingController::class,'store'])->name('store');
        Route::get('edit/{id}',[CommonSettingController::class,'edit'])->name('edit');
        Route::post('update',[CommonSettingController::class,'update'])->name('update');
        Route::post('destroy',[CommonSettingController::class,'destroy'])->name('destroy');
    });  

    Route::group(['prefix'=>'student','as'=>'student.'],function(){
        Route::get('create',[StudentController::class,'create'])->name('create');        
        Route::get('index',[StudentController::class,'index'])->name('index');
        Route::post('destroy',[StudentController::class,'destroy'])->name('destroy');
    });
    
    
    Route::group(['prefix'=>'course','as'=>'course.'],function(){
        Route::get('create',[CourseController::class,'create'])->name('create');        
        Route::get('index',[CourseController::class,'index'])->name('index');
        Route::get('edit/{id}',[CourseController::class,'edit'])->name('edit');
        Route::post('update',[CourseController::class,'update'])->name('update');
        Route::post('destroy',[CourseController::class,'destroy'])->name('destroy');
    });


    Route::group(['prefix'=>'merit','as'=>'merit.'],function(){
        Route::get('create',[MeritRoundController::class,'create'])->name('create');        
        Route::get('index',[MeritRoundController::class,'index'])->name('index');
        Route::post('store',[MeritRoundController::class,'store'])->name('store');
        Route::get('edit/{id}',[MeritRoundController::class,'edit'])->name('edit');
        Route::post('update',[MeritRoundController::class,'update'])->name('update');
        Route::post('destroy',[MeritRoundController::class,'destroy'])->name('destroy');
    });


    Route::group(['prefix'=>'admission','as'=>'admission.'],function(){
        Route::get('create',[AdmissionController::class,'create'])->name('create');        
        Route::get('index',[AdmissionController::class,'index'])->name('index');
        Route::post('destroy',[AdmissionController::class,'destroy'])->name('destroy');
    });
});


?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Student extends Authenticatable
{
    use HasFactory;

    protected $fillable = [
        'name','email','contact_no','email_verified_at','gender','address','otp','password','adhaar_card_no','image'
    ];
}

app/Http/Controllers/Student/AdmissionConfirmController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Models\Addmission;
use App\Models\AddmissionConfirmations;
use App\Models\MeritRound;
use App\Repository\AdmissionConfirmeRepository;
use Illuminate\Http\Request;

class AdmissionConfirmController extends Controller
{
    public function __construct(AdmissionConfirmeRepository $admissionconfirmRepository)
    {
        $this->admissionconfirmRepository = $admissionconfirmRepository;
    }

    public function store(Request $request)
    {
        $store = $this->admissionconfirmRepository->store($request);
        return response()->json($store); 
    }

    public function changeStatus(Request $request)
    {
        $user = Addmission::find($request->user_id);
        $user->status = $request->data_status;
        if ($request->data_status == 2) {
            $message = 'Rejected';
        } else if ($request->data_status == 0) {
            $message = 'You will appear next round';
        } else if ($request->data_status == 1) {
            $message = 'You will be selected';
        }else {
            $message = '';
        }
        $user->save();
        return response()->json(['message' => $message]);
    }
}

app/Http/Controllers/Student/AdmissionController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admission\StoreRequest;
use App\Models\Addmission;
use App\Models\College;
use App\Models\Course;
use App\Models\MeritRound;
use App\Models\StudentMark;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Validator;

class AdmissionController extends Controller
{
    public function create()
    {
        $course = Course::get();
        $collage = College::get();
        $merit_round = MeritRound::get();
        $dateYmd = date('Y-m-d');
        $form = MeritRound::where('start_date','<=',$dateYmd)->where('end_date','>=',$dateYmd)->first();
        return view('student.admission.create',compact('course','merit_round','collage','form'));
    }

    public function store(StoreRequest $request)
    {
        // $studentmark = StudentMark::with('commonsetting')->where('id', Auth::guard('student')->user()->id)->get();
        // // dd($studentmark);
        // $merit = 0;
        // $com_total = 0;
        // foreach ($studentmark as $studentmarks) {
        //     $total = ($studentmarks->obtain_mark * $studentmarks->commonsetting['marks'] ?? 0) / 100;
        //     $merit = $merit + $total;
        //     $com_total = $com_total + $studentmarks->commonsetting['marks'];
        // }
        // $f_merit = $merit / $com_total * 100;
        // dd($f_merit);        
        // dd($form);
        
        $student = StudentMark::where('id',Auth()->user()->id)->get();                   
        $course = Course::where('id',$request->course_id)->pluck('name')->first();  
        $addmission_code  = getRandomString($length = 6);
        $admission = new Addmission;
        $admission->user_id = request()->user()->id;
        $admission->merit = $request->merit;
        $admission->college_id = $request->college_id;
        $admission->addmission_date = $request->addmission_date;
        $admission->course_id = $request->course_id;    
        $admission->addmission_code = strtoupper($course) . $addmission_code;
        $admission->merit_round_id = $request->merit_round_no;
        $admission->status = 3;
        $admission->save();
        return response()->json('1');
    }  
    
    public function index(Request $request)
    {                
        $admission = Addmission::where('user_id',Auth()->user()->id)->first();              
        // $status = Addmission::where('user_id',Auth()->user()->id)->where('status',2)->first();               
        return view('student.admission.index',compact('admission'));
    }    
}
?>

app/Http/Controllers/Student/StudentController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;

class StudentController extends Controller
{
    public function profile()
    {
        $admin = Auth::guard('student')->user();
        return view('student.profile',compact('admin'));
    }

    public function updateprofile(Request $request)
    {              
        $admin = Auth::guard('student')->user();
        if ($request->hasFile('image')) {
            $destination = 'app/public/' . $admin->image;
            if (File::exists($destination)) {
                File::delete($destination);
            }
            $file = $request->file('image');
            $name = $file->getClientOriginalName();
            $file->move('app/public/', $name);
            $admin->image = $name;
        }
        $admin->name = $request->name;
        $admin->address = $request->address;
        $admin->save();
        session()->flash('update','Profile updated successfully');
        return redirect()->back();
    }

    public function changepassword()
    {
        return view('student.change_password');
    }

    public function updatepassword(Request $request)
    {
        $hashedPassword = Auth::guard('student')->user()->password;
        if (Hash::check($request->oldpassword, $hashedPassword)) {
            $update = bcrypt($request->newpassword);
            $users = Auth::guard('student')->id();
            $id = User::where('id', $users)->update(['password' => $update]);
            if ($id) {
                session()->flash('update', 'password updated successfully');
            }
            return redirect()->back();
        } else {
            session()->flash('error', 'old password doesnt matched');
            return redirect()->back();
        }
    }

}

app/Http/Controllers/Student/StudentMarkController.php
<?php

namespace App\Http\Controllers\Student;

use App\DataTables\StudentMarkDataTable;
use App\Http\Controllers\Controller;
use App\Http\Requests\StudentMark\StoreRequest;
use App\Models\StudentMark;
use App\Models\Subject;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class StudentMarkController extends Controller
{
    public function index(StudentMarkDataTable $studentmarkDataTable)
    {
        return  $studentmarkDataTable->render('student.mark.index');
    }

    public function create()
    {
        $subject = Subject::select('id', 'name')->get();
        return view('student.mark.create', compact('subject'));
    }

    public function store(StoreRequest $request)
    {
        $user_id = request()->user()->id;
        foreach ($request['subject_id'] as $key => $data) {
            StudentMark::create([
                'user_id' => $user_id,
                'subject_id' => $key,
                'total_mark' => $request->total_mark,
                'obtain_mark' => $data
            ]);
        }
        return response()->json('1');
    }

    public function edit(Request $id)
    {
        $subject = Subject::findOrFail($id);
        $student_mark = StudentMark::with('Subject')->where('user_id', Auth::guard('student')->user()->id)->get();
        return view('student.mark.edit', compact('student_mark'));
    }

    public function update(Request $request)
    {
        dd($request->all());
        $student_mark = StudentMark::find($request->id);
        $student_mark->subject_id = $request->subject_id;
        $student_mark->save();
        return response()->json(['property' => $student_mark]);
    }
}

app/Http/Controllers/University/AdmissionController.php
<?php

namespace App\Http\Controllers\University;

use App\DataTables\AdmissionDataTable;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdmissionController extends Controller
{
    public function index(AdmissionDataTable $admissionDataTable)
    {
        return  $admissionDataTable->render('admin.admission.index');
    }
}

app/Http/Controllers/University/StudentController.php
<?php

namespace App\Http\Controllers\University;

use App\DataTables\StudentDataTable;
use App\DataTables\UserDataTable;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    public function index(UserDataTable $userDataTable)
    {
        return  $userDataTable->render('admin.student.index') ;     
    }

    public function destroy(Request $request)
    {
        $student = User::where('id',$request->id)->delete();
        return response()->json(['student'=>$student]);
    }

}

resources/views/student/admission/create.blade.php
@extends('layouts.student.master')
@section('title','Admission')
@push('css')
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" rel="stylesheet" />
@endpush
@section('content')
<div class="content-wrapper">

    <section class="content">
        <div class="row">
            <div class="col-md-6">

                <div class="box box-primary ">
                    <div class="box-header with-border">
                        <h3 class="box-title">Admission</h3>
                    </div>
                    @if($form == NULL)
                        <div class="box-header with-border">
                            <h3 class="box-title" style="color:red">Form are now closed</h3>
                        </div>
                    @else
                    <form id="myform" method="post">
                        <div class="form-group ">
                            <label>Merit</label>
                            <input type="text" class="form-control" name="merit" placeholder="Enter merit">
                            <span class="glyphicon glyphicon-user form-control-feedback"></span>
                        </div>

                        <!-- <div class="form-group ">
                            <label>College_id</label>
                            <input type="text" class="form-control" name="college_id[]" placeholder="Enter collage">
                            <span class="glyphicon glyphicon-user form-control-feedback"></span>
                        </div> -->

                        <div class="form-group">
                            <label>College</label>
                            <select class="form-control" name="college_id[]" multiple id="college_id">
                                <option>--Select Collage--</option>
                                @foreach($collage as $c)
                                <option value="{{$c->id}}">{{$c->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Admission Date</label>
                            <input type="text" class="form-control" name="addmission_date" id="datepicker4" placeholder="Enter start date">
                        </div>

                        <div class="form-group">
                            <label>Course</label>
                            <select class="form-control" name="course_id" id="course_id">
                                <option>Select Course</option>
                                @foreach($course as $c)
                                <option value="{{$c->id}}">{{$c->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Merit Round</label>
                            <select class="form-control" name="merit_round_no" id="merit_round_no">
                                <option>Select Course</option>
                                @foreach($merit_round as $m)
                                <option value="{{$m->id}}">{{$m->round_no}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="row">
                            <div class="box-footer">
                                <button type="submit" autocomplete="off" id="submit" class="btn btn-primary btnsubmit">Submit</button>
                            </div>
                        </div>
                    </form>
                    @endif
                </div>              
            </div>
        </div>
    </section>
</div>
<div class="control-sidebar-bg"></div>
</div>
@endsection
@push('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>
<script>
    $(document).ready(function() {
        $("#submit").click(function(e) {
            e.preventDefault();
            var form = $("#myform")[0];
            var data = new FormData(form);
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: '{{route("student.admission.store")}}',
                type: 'post',
                data: data,
                cache: false,
                contentType: false,
                processData: false,
                dataType: 'JSON',
                success: function(result) {
                    swal({
                        title: "Inserted",
                        text: "Insert Succesfully!",
                        closeOnConfirm: false,
                        closeOnCancel: false,
                        buttons: ["Cancel", "Submit"]
                    }).then(function(isConfirm) {
                        if (isConfirm) {
                            $('#myform')[0].reset();
                            // window.location.href = '{{route("admin.admission.index")}}';
                        } else {
                            swal("Cancelled", "", "error")
                        }
                    });
                    $("#submit").attr("disabled", true);
                },
                error: function(result) {
                    $.each(result.responseJSON.errors, function(i, error) {
                        $('.' + i + 'error').empty();
                        var el = $(document).find('[name="' + i + '"]');
                        el.after($('<span class="' + i + 'error" style="color: red;">' + error[0] + '</span>'));
                    });
                }
            })
        });
    })


    //Store Date
    $('#datepicker4').datepicker({
        autoclose: true,
        format: 'yyyy-mm-dd',
        startDate: new Date()
    });
</script>

@endpush

resources/views/student/admission/index.blade.php
@extends('layouts.student.master')
@section('title','Admission')
@push('css')
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" rel="stylesheet" />
@endpush
@section('content')
<div class="content-wrapper">

    <section class="content ">
        <div class="row justify-content-center">
            <div class="col-md-6 form-group col-md-offset-3 align-center ">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Admission</h3>
                    </div>
                    <div id="messages"></div>
                    <div id="message"></div>
                    <form id="myform" method="post">
                        <div class="form-group">
                            <label>Merit</label>
                            <input type="text" value="{{$admission->merit}}" name="merit" class="form-control" readonly>
                        </div>

                        <div class="form-group">
                            <label>Course</label>
                            <input type="text" value="{{$admission->Course->name}}" name="course_id" class="form-control" readonly>
                        </div>

                        <div class="form-group">
                            <label>Merit Round</label>
                            <input type="text" value="{{$admission->merit_round_id}}" name="merit_round_id" class="form-control" readonly>
                        </div>

                        <div class="form-group">
                            <label>Admission Date</label>
                            <input type="text" value="{{$admission->addmission_date}}" name="addmission_date" class="form-control" readonly>
                        </div>

                        <div class="form-group">
                            <label>Admission Code</label>
                            <input type="text" value="{{$admission->addmission_code}}" name="addmission_code" class="form-control" readonly>
                        </div>

                        <div class="form-group">
                            <label>College</label>
                            <select class="form-control" name="college_id" id="college_id">
                                <option value="{{$admission->college_id[0]}}">{{$admission->college->name}}</option>
                            </select>
                        </div>

                        <input type="hidden" value="{{$admission->id}}" name="admission_id">
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success status" data-id="{{$admission->id}}" data-status="1" id="confirm" name="confirm" data-dismiss="modal">Confirm</button>
                            <button type="button" id="next" data-id="{{$admission->id}}" name="next" data-status="0" class="btn btn-primary status">Next Round</button>
                            <button type="button" id="reject" data-id="{{$admission->id}}" data-status="2" name="reject" class="btn btn-danger status">Reject</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
</div>
<div class="control-sidebar-bg"></div>
</div>
@endsection
@push('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>

<script>
    $(document).on("click", '.btnshow', function(e) {
        e.preventDefault();
        var url = $(this).attr("href");
        $.ajax({
            url: url,
            type: "GET",
            dataType: "JSON",
            success: function(data) {
                $("#set_name").text(data.name);
                $("#set_email").text(data.email);
                $("#set_mobile").text(data.mobile);
                $("#set_image").attr('src', data.image);
            }
        });
    });

    //Store Admission Confirmation
    $(document).ready(function() {
        $("#confirm").click(function(e) {
            e.preventDefault();
            var form = $("#myform")[0];
            var data = new FormData(form);
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: '{{route("student.admission_confirm.store")}}',
                type: 'post',
                data: data,
                cache: false,
                contentType: false,
                processData: false,
                dataType: 'JSON',
                success: function(result) {
                    swal({
                        title: "Inserted",
                        text: "Insert Succesfully!",
                        closeOnConfirm: false,
                        closeOnCancel: false,
                        buttons: ["Cancel", "Submit"]
                    }).then(function(isConfirm) {
                        if (isConfirm) {
                            $('#myform')[0].reset();
                        } else {
                            swal("Cancelled", "", "error")
                        }
                    });
                },
                error: function(result) {
                    $.each(result.responseJSON.errors, function(i, error) {
                        $('.' + i + 'error').empty();
                        var el = $(document).find('[name="' + i + '"]');
                        el.after($('<span class="' + i + 'error" style="color: red;">' + error[0] + '</span>'));
                    });
                }
            })
        });
    })

    $(function() {
        $(document).on("click", '.status', function(e) {
            var status = $(this).prop('checked') == true ? 1 : 0;
            var user_id = $(this).data('id');
            var data_status = $(this).attr('data-status');
            $.ajax({
                type: "GET",
                dataType: "json",
                url: '{{route("student.admission_confirm.changeStatus")}}',
                data: {
                    'status': status,
                    'user_id': user_id,
                    'data_status': data_status
                },
                success: function(res) {                  
                    var htm = "";
                    $('#messages').html();
                    htm = '<div class="message" style="color:red;text-align:center;font-size:18px">' + res.message + '</div>';
                    $('#messages').html(htm); 
                    $('#myform').hide();
                    $('#myform').val('');                   
                }
            });
        })
    })
</script>
@endpush